<?php

return [
    'segments' => [
        'law' => [
            ['code' => 'advocacia', 'label' => 'Advocacia'],
            ['code' => 'setor_publico', 'label' => 'Setor público'],
        ],
        'lead' => [
            ['code' => 'one', 'label' => 'One'],
            ['code' => 'team', 'label' => 'Team'],
        ],
    ],
    'contexts' => [
        'law' => [
            'advocacia' => [['code' => 'escritorio', 'label' => 'Escritório']],
            'setor_publico' => [
                ['code' => 'judiciario', 'label' => 'Judiciário'],
                ['code' => 'orgao_publico', 'label' => 'Órgão público'],
            ],
        ],
        'lead' => [
            'one' => [['code' => 'corretor_independente', 'label' => 'Corretor independente']],
            'team' => [['code' => 'imobiliaria_equipe', 'label' => 'Imobiliária/equipe']],
        ],
    ],
    'families' => [
        'law' => [
            ['code' => 'processos', 'label' => 'Processos'],
            ['code' => 'contatos', 'label' => 'Contatos'],
            ['code' => 'expedicoes', 'label' => 'Expedições'],
            ['code' => 'tarefas', 'label' => 'Tarefas'],
            ['code' => 'audiencias', 'label' => 'Audiências'],
        ],
        'lead' => [
            ['code' => 'pessoas', 'label' => 'Pessoas'],
            ['code' => 'imoveis', 'label' => 'Imóveis'],
            ['code' => 'empreendimentos', 'label' => 'Empreendimentos'],
            ['code' => 'leads', 'label' => 'Leads'],
            ['code' => 'funil', 'label' => 'Funil'],
            ['code' => 'website', 'label' => 'Website'],
            ['code' => 'relatorios', 'label' => 'Relatórios'],
            ['code' => 'notificacoes', 'label' => 'Notificações'],
        ],
    ],
    'personalization_types' => [
        ['code' => 'usuarios_ativos', 'label' => 'Usuários ativos', 'unit' => 'usuários'],
        ['code' => 'processos_ativos', 'label' => 'Processos ativos', 'unit' => 'processos'],
        ['code' => 'contatos_cadastrados', 'label' => 'Contatos cadastrados', 'unit' => 'contatos'],
        ['code' => 'imoveis_cadastrados', 'label' => 'Imóveis cadastrados', 'unit' => 'imóveis'],
        ['code' => 'empreendimentos_cadastrados', 'label' => 'Empreendimentos cadastrados', 'unit' => 'empreendimentos'],
        ['code' => 'expedicoes_mensais', 'label' => 'Expedições mensais', 'unit' => 'expedições/mês'],
        ['code' => 'relatorios_mensais', 'label' => 'Relatórios mensais', 'unit' => 'relatórios/mês'],
    ],
    'capabilities' => [
        'processos' => [
            ['code' => 'classes_assuntos_processuais', 'label' => 'Classes e assuntos processuais'],
            ['code' => 'prioridades_sigilo', 'label' => 'Prioridades e sigilo'],
            ['code' => 'integracao_datajud', 'label' => 'Integração Datajud'],
            ['code' => 'partes_processuais', 'label' => 'Partes processuais'],
            ['code' => 'andamentos_linha_tempo', 'label' => 'Andamentos e linha do tempo'],
        ],
        'contatos' => [
            ['code' => 'pessoas', 'label' => 'Pessoas'],
            ['code' => 'advogados', 'label' => 'Advogados'],
            ['code' => 'partes_processuais', 'label' => 'Partes processuais'],
            ['code' => 'orgaos_publicos', 'label' => 'Órgãos públicos'],
            ['code' => 'vinculacao_processos_expedicoes_tarefas', 'label' => 'Vinculação em processos, expedições e tarefas', 'optional' => true],
        ],
        'expedicoes' => [
            ['code' => 'oficios', 'label' => 'Ofícios'],
            ['code' => 'mandados', 'label' => 'Mandados'],
            ['code' => 'cartas_precatorias', 'label' => 'Cartas precatórias'],
            ['code' => 'cartas_rogatorias', 'label' => 'Cartas rogatórias'],
            ['code' => 'cartas_ordem', 'label' => 'Cartas de ordem'],
            ['code' => 'editais', 'label' => 'Editais'],
            ['code' => 'guias_execucao', 'label' => 'Guias de execução'],
            ['code' => 'atos_ordinatorios', 'label' => 'Atos ordinatórios'],
        ],
        'tarefas' => [
            ['code' => 'tarefas', 'label' => 'Tarefas'],
            ['code' => 'prazos', 'label' => 'Prazos'],
            ['code' => 'alertas', 'label' => 'Alertas'],
            ['code' => 'pendencias', 'label' => 'Pendências'],
            ['code' => 'fluxos_trabalho', 'label' => 'Fluxos de trabalho'],
        ],
        'audiencias' => [
            ['code' => 'agenda_audiencias', 'label' => 'Agenda de audiências'],
            ['code' => 'participantes', 'label' => 'Participantes'],
            ['code' => 'pauta', 'label' => 'Pauta'],
            ['code' => 'atas', 'label' => 'Atas'],
            ['code' => 'situacao_historico', 'label' => 'Situação e histórico'],
            ['code' => 'alertas_notificacoes', 'label' => 'Alertas e notificações'],
            ['code' => 'cadastro_estudante_solicitacao_acesso', 'label' => 'Cadastro de estudante e solicitação de acesso à audiência'],
            ['code' => 'acesso_link_audiencia', 'label' => 'Acesso ao link da audiência'],
            ['code' => 'pauta_limitada', 'label' => 'Pauta de audiência limitada'],
            ['code' => 'painel_audiencias_dia', 'label' => 'Painel de audiências do dia'],
        ],
        'pessoas' => [
            ['code' => 'cadastro_pessoas', 'label' => 'Cadastro de pessoas'],
            ['code' => 'dados_contato', 'label' => 'Dados de contato'],
            ['code' => 'origem_contato', 'label' => 'Origem do contato'],
            ['code' => 'preferencias_imovel', 'label' => 'Preferências de imóvel'],
            ['code' => 'historico_relacionamento', 'label' => 'Histórico de relacionamento'],
            ['code' => 'classificacao_interesse', 'label' => 'Classificação de interesse'],
        ],
        'imoveis' => [
            ['code' => 'cadastro_imoveis', 'label' => 'Cadastro de imóveis'],
            ['code' => 'caracteristicas_localizacao', 'label' => 'Características e localização'],
            ['code' => 'disponibilidade', 'label' => 'Disponibilidade'],
            ['code' => 'valores_condicoes', 'label' => 'Valores e condições'],
            ['code' => 'proprietarios_responsaveis', 'label' => 'Proprietários e responsáveis'],
            ['code' => 'status_publicacao', 'label' => 'Status de publicação'],
        ],
        'empreendimentos' => [
            ['code' => 'cadastro_empreendimentos', 'label' => 'Cadastro de empreendimentos'],
            ['code' => 'localizacao_caracteristicas', 'label' => 'Localização e características'],
            ['code' => 'unidades_vinculadas', 'label' => 'Unidades vinculadas'],
            ['code' => 'tabela_precos', 'label' => 'Tabela de preços'],
            ['code' => 'status_comercial', 'label' => 'Status comercial'],
        ],
        'leads' => [
            ['code' => 'cadastro_leads', 'label' => 'Cadastro de leads'],
            ['code' => 'origem_lead', 'label' => 'Origem do lead'],
            ['code' => 'qualificacao', 'label' => 'Qualificação'],
            ['code' => 'responsavel_comercial', 'label' => 'Responsável comercial'],
            ['code' => 'interacoes', 'label' => 'Interações'],
            ['code' => 'conversao_cliente', 'label' => 'Conversão em cliente'],
            ['code' => 'historico_lead', 'label' => 'Histórico do lead'],
        ],
        'funil' => [
            ['code' => 'etapas_personalizaveis', 'label' => 'Etapas personalizáveis'],
            ['code' => 'oportunidades', 'label' => 'Oportunidades'],
            ['code' => 'movimentacao_etapas', 'label' => 'Movimentação de etapas'],
            ['code' => 'responsavel_comercial', 'label' => 'Responsável comercial'],
            ['code' => 'previsao_fechamento', 'label' => 'Previsão de fechamento'],
            ['code' => 'historico_negociacao', 'label' => 'Histórico de negociação'],
        ],
        'website' => [
            ['code' => 'formularios_interesse', 'label' => 'Formulários de interesse'],
            ['code' => 'recebimento_leads', 'label' => 'Recebimento de leads'],
            ['code' => 'origem_identificada', 'label' => 'Origem identificada'],
            ['code' => 'distribuicao_responsaveis', 'label' => 'Distribuição para responsáveis'],
            ['code' => 'integracao_imoveis', 'label' => 'Integração com imóveis'],
            ['code' => 'rastreamento_conversao', 'label' => 'Rastreamento de conversão'],
        ],
        'relatorios' => [
            ['code' => 'relatorios_transacoes', 'label' => 'Relatórios de transações'],
            ['code' => 'relatorios_imoveis', 'label' => 'Relatórios de imóveis'],
            ['code' => 'relatorios_leads', 'label' => 'Relatórios de leads'],
        ],
        'notificacoes' => [
            ['code' => 'alertas_novos_leads', 'label' => 'Alertas de novos leads'],
            ['code' => 'lembretes_atendimento', 'label' => 'Lembretes de atendimento'],
            ['code' => 'avisos_movimentacao_funil', 'label' => 'Avisos de movimentação no funil'],
        ],
    ],
];
